# Generated by Django 5.2.4 on 2025-07-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_attachment_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. 'knee_angle'", max_length=100)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], help_text='Which side of the body this metric applies to', max_length=6)),
                ('slug', models.SlugField(help_text="Machine-friendly identifier, e.g. 'left_knee_angle'", unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional human-readable description')),
                ('landmark_indexes', models.JSONField(default=list, help_text='List of MediaPipe landmark indexes used in this calculation, e.g. [23,25,27] for hip→knee→ankle')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tasks.attachment')),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tasks.metricarchetype')),
            ],
            options={
                'indexes': [models.Index(fields=['archetype', 'computed_at'], name='tasks_metri_archety_ea7180_idx')],
                'unique_together': {('attachment', 'archetype')},
            },
        ),
        migrations.CreateModel(
            name='PostLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_index', models.PositiveIntegerField(help_text='Index of body landmark location in the attachment image.')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='tasks.attachment')),
            ],
            options={
                'indexes': [models.Index(fields=['attachment', 'location_index'], name='tasks_postl_attachm_e3f511_idx')],
                'unique_together': {('attachment', 'location_index')},
            },
        ),
    ]
