# Generated by Django 5.2.4 on 2025-07-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_metricarchetype_metric_postlandmark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLandmark',
            new_name='PoseLandmark',
        ),
        migrations.RenameIndex(
            model_name='poselandmark',
            new_name='tasks_posel_attachm_c7526a_idx',
            old_name='tasks_postl_attachm_e3f511_idx',
        ),
    ]
