# Generated by Django 5.2.4 on 2025-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_postlandmark_poselandmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poselandmark',
            name='presence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
